version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      - DOCUMENT_ROOT=/var/www/html/public
      - SS_TRUSTED_PROXY_IPS=*
      - SS_ENVIRONMENT_TYPE=dev
      - SS_DATABASE_SERVER=database
      - SS_DATABASE_NAME=basekit
      - SS_DATABASE_USERNAME=root
      - SS_DATABASE_PASSWORD=
      - SS_DEFAULT_ADMIN_USERNAME=admin
      - SS_DEFAULT_ADMIN_PASSWORD=admin
      - SS_ERROR_LOG=silverstripe.log
  database:
    image: mysql:8.0
    restart: always
    ports:
      - 9306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
